Algoritmo "contador_decimal2"

// Disciplina  : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : Aula 11 – Estruturas de Repetição 3
// Autor(a)    : Nikitha De Angelis
// Ano         : 2021

Var

   // Variáveis
   contador: inteiro

Inicio

      // Contador com FOR:
      Escreval("Olá! Sou um contador! Conto até 10!")
      Para contador <- 1 ate 10 faca
             Escreval(contador)
      FimPara
      Escreval("Terminei de contar!")
      
Fimalgoritmo